# Generated by Django 6.0.3 on 2026-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
