# Generated by Django 6.0.3 on 2026-03-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dci', models.CharField(blank=True, max_length=200)),
                ('forme', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.PositiveIntegerField(default=0)),
                ('stock_minimum', models.PositiveIntegerField(default=10)),
                ('date_expiration', models.DateField()),
                ('ordonnance_requise', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
